"""Add position column to boards table

Revision ID: 3dd54e08d506
Revises: 561aa65385ab
Create Date: 2025-11-09 13:31:44.208565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3dd54e08d506'
down_revision: Union[str, Sequence[str], None] = '561aa65385ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boards', sa.Column('position', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('boards', 'position')
    # ### end Alembic commands ###
